CREATE TABLE IF NOT EXISTS drinks (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  caffeine_mg INTEGER NOT NULL,
  is_custom BOOLEAN DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS intake_logs (
  id SERIAL PRIMARY KEY,
  drink_id INTEGER NOT NULL,
  consumed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (drink_id)
    REFERENCES drinks(id)
    ON DELETE CASCADE
);
