INSERT INTO drinks (name, caffeine_mg, is_custom) VALUES
('Espresso', 63, false),
('Americano', 95, false),
('Latte', 80, false),
('Cappuccino', 80, false),
('Flat White', 130, false),
('Tea', 24, false),
('Green Tea', 28, false),
('Monster Energy', 160, false),
('Red Bull', 147, false),
('Cola', 34, false),
('Diet Coke', 46, false),
('Hot Chocolate', 25, false),
('Double Espresso', 126, false),
('Triple Espresso', 189, false),
('Mocha', 90, false),
('Iced Coffee', 95, false),
('Cold Brew', 155, false),
('Decaf Coffee', 5, false),
('Chai Latte', 40, false),
('Matcha Latte', 70, false),
('White Tea', 15, false),
('Oolong Tea', 38, false),
('Iced Tea', 30, false),
('Pepsi', 38, false),
('Dr Pepper', 41, false),
('Lucozade', 46, false);